export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSE_SUCCESS = 'LOAD_COURSE_SUCCESS';
export const ADD_COURSE_PLAN_ITEM = 'ADD_COURSE_PLAN_ITEM';

export const LOAD_GROUPS_SUCCESS = 'LOAD_GROUPS_SUCCESS';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';